### ISSUE TITLE
New feature: Filters for seminars

### ISSUE THREAD

**Issue by jeff-saupe** [coderesting/NAKExtension#18]
It'd be a great feature when filters would be implemented into the Seminare page.

Examples could be:
- filtering by categories
- filtering by the workload (e.g. shortest/longest seminars)
- filtering by the type of examination (e.g. oral or written)
- filtering by the amount of credit points

All information can be obtained through the page of seminar, e.g.:

![image](https://user-images.githubusercontent.com/46161762/119989629-b02bf500-bfc7-11eb-8fb0-2bf46a462808.png)

![image](https://user-images.githubusercontent.com/46161762/124305131-f810df80-db64-11eb-87ba-de235bc72cce.png)

**Comment by IceToast** [comment]
You should keep in mind to blur out the names of the lecturer ^^

**Comment by IceToast** [comment]
I checked some of your ideas:
- filtering by categories (more than one category I suspect) seems to be pretty simple

For the other three, you need the information from each seminar page (e.g. requesting every seminar page to gather all information) which will take some time to initialize the filtering feature

**Comment by IceToast** [comment]
> For the other three, you need the information from each seminar page (e.g. requesting every seminar page to gather all information) which will take some time to initialize the filtering feature

I tested requesting each seminar page in order to get the desired information, but it seems to be complicated.

```
function requestEverySeminar() {
	let table = document.getElementById("seminar-table-")
	let rows = table.rows
	let seminars = Array.from(rows);
	seminars.shift()
	
	seminars.forEach(seminar => {
		let href = seminar.cells[0].children[0].href
		
		fetch(href, {method: "GET", redirect :"manual"})
		   .then(res => {console.log("fetch successful")})
		   .catch(error => console.log("fetch failed"))
	}) 
}
```

If you test this function (simply requesting each seminar page) you will notice that most requests will be redirected to /login.
![image](https://user-images.githubusercontent.com/54889359/123700138-5c2f5d00-d860-11eb-8f63-d63c2f1e61ff.png)

For my understanding, you have to time every request and validate their responses, in order to get the information for each seminar.

**Comment by IceToast** [comment]
Me again 👯 
I found out that you could get any information about a seminar from that nak page directly:
[Studium Generale](https://www.nordakademie.de/studium-generale)

But you have to map each seminar on this page to the seminar table from the CIS via string matching. I haven't checked if the seminar titles are the same all the time

**Comment by coderesting** [comment]
@IceToast, @jeff-saupe
String matching seems more plausible for me than requesting every seminar page (we could even reuse the string matcher for moodle courses).
I'd like to pack a new version with the fix for #21 within the next few weeks. 
If one of you would like to give this filtering a shot I could add it to the next release.

FYI: The extension got kicked out of the mozilla store for having no broad audience. (The next firefox release will probably be self hosted)

**Comment by IceToast** [comment]
@coderesting Tried some requests to get the table content from the homepage of the nordakademie but it seems they have blocked every request outside from the same origin -> nordakademie.de.
It Also seems they have set the strict-origin policy so not even a request from a subdomain will work here. 

Maybe you could find a setting to get a response but other than that i think this won't be possible

**Comment by coderesting** [comment]
Ok I will close this issue for now.
We can reopen the issue if we find a solution in the future.
